### ISSUE TITLE
 minimized  file does not enable 'extraClasses' option

### ISSUE THREAD

**Issue by WangJi** [lennardv2/Leaflet.awesome-markers#32]
Seems strange but I'm afraid it's real:

The 'leaflet.awesome-markers.min.js' file in version "2.0.1" just does not extend the 'extraClasses' option.

**Comment by adriennn** [comment]
the non-minified version 2.0.1 doesn't extend the `extraClasses` option either.
To achieve what the `extraClasses` function should do, one needs to use:

``` javascript
     var myMarkerIcon = L.AwesomeMarkers.icon({
                icon: 'fa-question',
                extraClasses: 'my-awesome-marker',
                className: 'awesome-marker my-awesome-marker'
            });
```

In fact one can omit the `extraClasses` option but if you use `className` make certain you re-add the `awesome-marker` class else it will disappear and the icons won't show.

 `extraClasses` values get added to the `<i>` tag of the marker while the `className` is set on the actual `<div>`.
