### ISSUE TITLE
bower registration

### ISSUE THREAD

**Issue by houqp** [lennardv2/Leaflet.awesome-markers#7]
would you mind register the project in bower? That will make it a lot easier for us to manage dependency :)

**Comment by crucialfelix** [comment]
++ I install most of my dependencies via bower too.  I had to copy this one in manually.  thanks !

**Comment by lennardv2** [comment]
Added version 1.0.0 and version 2.0.0 to bower

**Comment by crucialfelix** [comment]
Thanks !
