### ISSUE TITLE
Example is broken.

### ISSUE THREAD

**Issue by blowsie** [lennardv2/Leaflet.awesome-markers#8]
github doesnt allow script requests from external sources any more, as a result the jsfiddle is broken.

![image](https://f.cloud.github.com/assets/308572/768618/c287cd18-e8a3-11e2-8165-68e3e71a65cc.png)

**Comment by walesmd** [comment]
[This jsFiddle](http://jsfiddle.net/VPzu4/28/) will work in the interim; I just copied the minified version directly into JavaScript pane. If anyone has a bit of spare time, I would recommend getting this added into [cdnjs](http://cdnjs.com/).
