### ISSUE TITLE
Supported colors - confusing readme

### ISSUE THREAD

**Issue by Krb686** [lennardv2/Leaflet.awesome-markers#9]
The readme here seems a bit confusing.  At one point you say the supported colors are:

```
'red'
'darkred'
'orange'
'green'
'darkgreen'
'blue'
'darkblue'
'purple'
'darkpurple'
'cadetblue'
```

Then just below that, you say the only icon colors you can have are:

white
black

So which one is it? It seems that by testing it out it appears to be white and black.

If that's supposed to be the only colors supported by Font-Awesome, maybe that should be a sub-category while the other colors are Twitter-bootstrap, they should be a subcategory of that.  Or if that is supposed to be the only colors supported by spinning icons, it should be indented below that. It's kind of confusing the way it is.  Also, your example has:

```
icon: 'red'
```

but upon using that code, the icons appear to be limited to black and white.  So it doesn't seem like black and white are limited to just spinning icons, but all icons.

And one more thing, you should also put under the **Using the plugin** part at the top, "make sure to include font-awesome.css in your html, downloaded from....  I know you said "This plugin depends on Bootstrap or Font-Awesome for the rendering of the icons.", but it makes sense to have a clear section that tells people everything they need to do to get it working right in front of them, rather than split up among sections.

Just my 2c

Other than that, cool plugin!

**Comment by lennardv2** [comment]
Hi there krb686,

Thanks for your feedback. Feel free to make the changes to the readme and do a pull request. I will be happy to merge it!

Thanks in advance,
Lennard

**Comment by lennardv2** [comment]
I renamed this to iconColor for the icons and markerColor for the marker. Hope this is clear now
