### ISSUE TITLE
Icon shows, but no balloon

### ISSUE THREAD

**Issue by codeswayslay** [lennardv2/Leaflet.awesome-markers#95]
After following the tutorial, for some reason, the icon shows, but the balloon that should surround the icon doesn't show. Has something changed?

If I do this:
`L.marker([51.344853, 0.098877]).addTo(mymap);`
The default balloon marker shows.

If I do this:
```
var redMarker = L.AwesomeMarkers.icon({
        icon: 'coffee',
        iconColor: 'black',
        prefix: 'fa',
        markerColor: 'red'
});
L.marker([51.344853, 0.098877], {icon: redMarker}).addTo(mymap);
```
Only the coffee icon shows.

I thought the icon and the balloon are supposed to come as one, or is there something else to configure?

Thanks.

**Comment by lowndes783** [comment]
I'm having the same issue. Anyone know why?

**Comment by lowndes783** [comment]
Worked it out, you need to add the 'images' folder in the same directory as the 'leaflet.awesome-markers.css'

**Comment by codeswayslay** [comment]
Thanks a lot!

**Comment by nojcc** [comment]
The images folder is there for me but I still don't see the balloon
